name: Deploy to github pages

on:
  push:
    branches:
      - main

jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1
          with:
            version:  12.x
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Set homepage - ${{ github.repository }}
          run: |
            IFS="/" read -a a <<< ${{ github.repository }}
            sed -i "s/layik/${a[0]}/" package.json
            sed -i "s/eatlas-template/${a[1]}/" package.json
            # debug
            cat package.json
        - name: Install dependencies
          run: yarn install
    
        - name: Build
          run: yarn run build
          env:
            CI: false
            REACT_APP_DEFAULT_URL: https://raw.githubusercontent.com/layik/eatlas-data/main/casualties.csv 
            REACT_APP_MAPBOX_ACCESS_TOKEN: ${{secrets.MAPBOX_KEY}}

        - name: Run deploy script
          # git config is required
          run: |
            git config user.name "github-actions[bot]" 
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout --orphan gh-pages
            git --work-tree build add --all
            git --work-tree build commit -m 'Deploy'
            git push origin HEAD:gh-pages --force

